/* eslint-disable import/prefer-default-export */

export const CHANGE_RESOLUTION = 'CHANGE_RESOLUTION';
// Auth
export const AUTH_SET_LOGIN_STATUS = 'AUTH_SET_LOGIN_STATUS';
// banners
export const BANNERS_RECEIVED = 'BANNERS_RECEIVED';
export const BANNERS_FETCHING = 'BANNERS_FETCHING';
// recommends
export const RECOMMENDS_RECEIVED = 'RECOMMENDS_RECEIVED';
export const RECOMMENDS_FETCHING = 'RECOMMENDS_FETCHING';
// items
export const ITEMS_FETCHING = 'ITEMS_FETCHING';
export const ITEMS_FETCHED = 'ITEMS_FETCHED';
export const ITEMS_CATEGORIES_FETCHING = 'ITEMS_CATEGORIES_FETCHING';
export const ITEMS_CATEGORIES_FETCHED = 'ITEMS_CATEGORIES_FETCHED';
// item layout
export const ITEM_LAYOUT_CHANGE_CURRENT_NAV = 'ITEM_LAYOUT_CHANGE_CURRENT_NAV';
// release item form set
export const ITEM_RELEASE_SET_TITLE = 'ITEM_RELEASE_SET_TITLE';
export const ITEM_RELEASE_SET_DESCRIPTION = 'ITEM_RELEASE_SET_DESCRIPTION';
export const ITEM_RELEASE_FORM_SET_CITYZONE = 'ITEM_RELEASE_FORM_SET_CITYZONE';
export const ITEM_RELEASE_FORM_SET_SHIPPING = 'ITEM_RELEASE_FORM_SET_SHIPPING';
export const ITEM_RELEASE_FORM_SET_SHIPPING_DAYS = 'ITEM_RELEASE_FORM_SET_SHIPPING_DAYS';

// address cities
export const ADDRESS_SET_CITIES = 'ADDRESS_SET_CITIES';
export const ADDRESS_SET_ZONES = 'ADDRESS_SET_ZONES';

// new publish
// CROPPER
export const PUBLISH_OEPN_CROPPER = 'PUBLISH_OEPN_CROPPER';
export const PUBLISH_CLOSE_CROPPER = 'PUBLISH_CLOSE_CROPPER';
// THUMBS
export const PUBLISH_THUMBS_CREATE = 'PUBLISH_THUMBS_CREATE';
export const PUBLISH_THUMBS_UPDATE_ORDERS = 'PUBLISH_THUMBS_UPDATE_ORDERS';
export const PUBLISH_THUMBS_REMOVE_ONE = 'PUBLISH_THUMBS_REMOVE_ONE';
export const PUBLISH_THUMBS_UPDATING_ONE = 'PUBLISH_THUMBS_UPDATING_ONE';
export const PUBLISH_THUMBS_UPDATED_ONE = 'PUBLISH_THUMBS_UPDATED_ONE';
