class Response::ErrorCode

  SUCCESS = 0
  USER_NOT_EXIST = 1
  USER_EXIST = 2
  VERIFY_CODE_NOT_CORRECT = 3
  LOGIN_PASSWORD_ERROR = 4
  FB_LOGIN_ERROR = 5
  PID_NOT_EXIST = 6
  PID_EXIST = 7
  CONTRACT_NOT_EXIST = 8
  CONTRACT_EXIST = 9
  NEW_EMAIL_ALREADY_EXIST = 10

  USER_EMAIL_NOT_VERIFY = 11 # REGISTER
  ALL_CONFIRM = 12
  USER_MOBILE_NOT_VERIFY = 13
  NEW_MOBILE_ALREADY_EXIST = 14
  TOKEN_EXPIRED = 15
  TOKEN_NOT_EXIST = 16
  REPORT_EXIST = 17
  CONSTRACT_STAGE_ERROR = 18
  ORDER_NOT_EXIST = 19
  ITEM_CATEGORY_NOT_EXIST = 20

  FACEBOOK_ACCESS_ERROR = 21
  ILLEGAL_BANKINFO_FORMAT = 22
  NO_AUTHROIZATION_TO_ACCESS = 23
  REQUESTED_FORMAT_ERROR_PLEASE_CHECK_AGAIN = 24
  CONTRACT_WAS_UPDATED = 25
  VERIFY_CODE_EXPIRED = 26
  ITEM_IS_DISABLED = 27
  NOT_STOCK = 28
  USER_REPORT_NOT_EXIST = 29
  PERMISSION_DENIED = 30

  DB_EXCEPTION = 31
  INTERNAL_EXCEPTION = 32
  JSON_PARSE_EXCEPTION = 33
  LOGISTICS_ORDER_STAGE_ERROR = 34
  LOGISTICS_ORDER_NOT_EXIST = 35
  CATEGORY_MUST_BELONG_ITEM = 36
  CATEGORY_MUST_BELONG_SERVICE = 37
  CATEGORY_MUST_BELONG_SPACE = 38
  LEASE_TERM_LESS_THAN_MIN_LEASE_DAYS = 39

  COUPON_NO_EXIST = 40
  
  MESSAGE_MAPPING = {
    SUCCESS => '成功',
    USER_NOT_EXIST => '帳號不存在',
    USER_EXIST => '帳號已存在',
    VERIFY_CODE_NOT_CORRECT => '驗證碼錯誤,請再確認一次',
    LOGIN_PASSWORD_ERROR => '密碼錯誤',
    FB_LOGIN_ERROR => '臉書登入失敗',
    PID_NOT_EXIST => '商品不存在',
    PID_EXIST => '商品已存在',
    CONTRACT_NOT_EXIST => '合約不存在',
    CONTRACT_EXIST => '合約已存在',
    NEW_EMAIL_ALREADY_EXIST => '信箱已被註冊過',

    USER_EMAIL_NOT_VERIFY => '信箱尚未驗證', # REGISTER
    ALL_CONFIRM => '合約簽署成功',
    USER_MOBILE_NOT_VERIFY => '手機號碼尚未驗證',
    NEW_MOBILE_ALREADY_EXIST => '手機號碼已被註冊過',
    TOKEN_EXPIRED => '系統錯誤',
    TOKEN_NOT_EXIST => '帳號已登出',
    REPORT_EXIST => '申訴已提出',
    CONSTRACT_STAGE_ERROR => '合約狀態錯誤',
    ORDER_NOT_EXIST => '訂單不存在',
    ITEM_CATEGORY_NOT_EXIST => '商品類型不存在',

    FACEBOOK_ACCESS_ERROR => '臉書錯誤',
    ILLEGAL_BANKINFO_FORMAT => '銀行帳戶錯誤',
    NO_AUTHROIZATION_TO_ACCESS => '無存取權限',
    REQUESTED_FORMAT_ERROR_PLEASE_CHECK_AGAIN => '系統格式錯誤',
    CONTRACT_WAS_UPDATED => '合約已被更新過',
    VERIFY_CODE_EXPIRED => '驗證碼過期',
    ITEM_IS_DISABLED => '商品已下架',
    NOT_STOCK => '商品已無庫存',
    USER_REPORT_NOT_EXIST => '申訴紀錄不存在',
    PERMISSION_DENIED => '不可將自己的商品加入我的最愛',

    DB_EXCEPTION => '系統錯誤',
    INTERNAL_EXCEPTION => '系統錯誤',
    JSON_PARSE_EXCEPTION => 'JSON格式錯誤',
    LOGISTICS_ORDER_STAGE_ERROR => '物流訂單錯誤',
    LOGISTICS_ORDER_NOT_EXIST => '物流訂單不存在',
    CATEGORY_MUST_BELONG_ITEM => '類型不屬於商品',
    CATEGORY_MUST_BELONG_SERVICE => '類型不屬於服務',
    CATEGORY_MUST_BELONG_SPACE => '類型不屬於空間',
    LEASE_TERM_LESS_THAN_MIN_LEASE_DAYS => '租期小於最短租期',
    
    COUPON_NO_EXIST => '優惠卷不存在',
  }

  class << self
    def localize code
      MESSAGE_MAPPING[code.to_i]
    end
  end
end
