export default [
  { faClass: 'suitcase', text: '全部物品' },
  { faClass: 'car', text: '交通工具' },
  {
    faClass: 'flash',
    text: '3C',
    subcates: [
      { text: '精品配件' },
      { text: '婦幼' },
      { text: '遊戲' },
      { text: '生活用品' },
      { text: '服飾' },
      { text: '鞋子' },
      { text: '包包' },
      { text: '書籍' },
      { text: '樂器' },
    ],
  },
  { faClass: 'desktop', text: '家電' },
  { faClass: 'camera-retro', text: '相機攝影' },
  { faClass: 'soccer-ball-o', text: '運動休閒' },
  { faClass: 'apple', text: '精品配件' },
  { faClass: 'child', text: '婦幼' },
  { faClass: 'gamepad', text: '遊戲' },
  { faClass: 'shopping-basket', text: '生活用品' },
  { faClass: 'cut', text: '服飾' },
  { faClass: 'suitcase', text: '鞋子' },
  { faClass: 'suitcase', text: '包包' },
  { faClass: 'suitcase', text: '書籍' },
  {
    faClass: 'suitcase',
    text: '樂器',
    subcates: [
      { text: '吉他' },
      { text: '烏克麗麗' },
      { text: '貝斯' },
      { text: '打擊樂器' },
      { text: '鍵盤樂器' },
      { text: '音箱' },
      { text: '樂器配件' },
      { text: '其他' },
    ],
  },
];
