/* eslint-disable import/prefer-default-export */

export const CHANGE_RESOLUTION = 'CHANGE_RESOLUTION';
export const ENVIRONMENT_CHANGE_SCROLLTOP = 'ENVIRONMENT_CHANGE_SCROLLTOP';
export const ENVIRONMENT_CHECK_ITEMS_LAYOUT_FIXED = 'ENVIRONMENT_CHECK_ITEMS_LAYOUT_FIXED';
// Auth
export const AUTH_SET_LOGIN_STATUS = 'AUTH_SET_LOGIN_STATUS';
// banners
export const BANNERS_RECEIVED = 'BANNERS_RECEIVED';
export const BANNERS_FETCHING = 'BANNERS_FETCHING';
// recommends
export const RECOMMENDS_RECEIVED = 'RECOMMENDS_RECEIVED';
export const RECOMMENDS_FETCHING = 'RECOMMENDS_FETCHING';
// items
export const ITEMS_FETCHING = 'ITEMS_FETCHING';
export const ITEMS_FETCHED = 'ITEMS_FETCHED';
export const ITEMS_CATEGORIES_FETCHING = 'ITEMS_CATEGORIES_FETCHING';
export const ITEMS_CATEGORIES_FETCHED = 'ITEMS_CATEGORIES_FETCHED';
