defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  jwt:
    expiration_hours: 6
    secret: 'jwt secret key'

development:
  <<: *defaults
  api_base_uri: http://debug.shareapp.com.tw:18080/ShareAPI-1.3.1

test:
  <<: *defaults

production:
  <<: *defaults
  jwt_secret: 'jwt secret key'
