defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  jwt:
    expiration_hours: 6
    secret: 'jwt secret key'

development:
  <<: *defaults
  api_base_uri: http://debug.shareapp.com.tw:18080/ShareAPI
  s3_bucket:
    wish: wish_debug
    return: return_debug
    ship: ship_debug
    sue: sue_debug
test:
  <<: *defaults

production:
  <<: *defaults
  jwt_secret: 'jwt secret key'
  api_base_uri: https://api.shareapp.com.tw/ShareAPI
  s3_bucket:
    wish: wish
    return: return
    ship: ship
    sue: sue
