defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  jwt:
    expiration_hours: 6
    secret: 'jwt secret key'

development:
  <<: *defaults
  # api_base_uri: http://debug.shareapp.com.tw:18080/ShareAPI
  api_base_uri: https://debug.shareapp.com.tw:18443/ShareAPI
  domain: debug.shareapp.com.tw
  s3_bucket:
    wish: wish_debug
    return: return_debug
    ship: ship_debug
    sue: sue_debug
  api_iot_base_uri: http://211.20.1.240:18080/ShareApiIoT
  api_iot_certificate: mYteQnom66OAOYkwnxXcyMSual3bM0qLzWlDGsmr+DrJ6yEpMQBxjTrgoVh8O3lVNqoAb2DY+DpqYZteGLX+WzRUN1SBeF93iCWqNpd7ICg=

test:
  <<: *defaults
  api_iot_certificate: mYteQnom66OAOYkwnxXcyMSual3bM0qLzWlDGsmr+DrJ6yEpMQBxjTrgoVh8O3lVNqoAb2DY+DpqYZteGLX+WzRUN1SBeF93iCWqNpd7ICg=
production:
  <<: *defaults
  jwt_secret: 'jwt secret key'
  api_base_uri: https://api.shareapp.com.tw/ShareAPI
  domain: web.shareapp.com.tw
  s3_bucket:
    wish: wish
    return: return
    ship: ship
    sue: sue
