defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  jwt:
    expiration_hours: 6
    secret: 'jwt secret key'

development:
  <<: *defaults
  api_base_uri: http://debug.shareapp.com.tw:18080/ShareAPI
  api_iot_base_uri: http://211.20.1.240:18080/ShareApiIoT
  api_iot_certificate: mYteQnom66OAOYkwnxXcyMSual3bM0qLzWlDGsmr+DrJ6yEpMQBxjTrgoVh8O3lVNqoAb2DY+DpqYZteGLX+WzRUN1SBeF93iCWqNpd7ICg=
test:
  <<: *defaults
  api_iot_certificate: mYteQnom66OAOYkwnxXcyMSual3bM0qLzWlDGsmr+DrJ6yEpMQBxjTrgoVh8O3lVNqoAb2DY+DpqYZteGLX+WzRUN1SBeF93iCWqNpd7ICg=
production:
  <<: *defaults
  jwt_secret: 'jwt secret key'
